<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-10-18 17:30

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 6.0.2 on 2026-02-10 11:17

import django.db.models.deletion
from django.db import migrations, models
>>>>>>> create_addresses-app


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('billing', '0001_initial'),
=======
        ('billing', '0002_alter_billingprofile_id'),
>>>>>>> create_addresses-app
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> create_addresses-app
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=120)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(default='Brazil', max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=120)),
                ('billing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billingprofile')),
            ],
        ),
    ]
