# Generated by Django 6.0.2 on 2026-02-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_country'),
        ('addresses', '0002_alter_address_id'),
    ]

    operations = [
    ]
