<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-07-27 13:00
=======
# Generated by Django 6.0.2 on 2026-02-09 17:54
>>>>>>> refresh_cart_ajax

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
