# Generated by Django 6.0.2 on 2026-02-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211031_2330'),
        ('orders', '0005_order_billing_address_order_shipping_address'),
    ]

    operations = [
    ]
