# Generated by Django 6.0.2 on 2026-02-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_id'),
        ('orders', '0006_merge_20260214_1022'),
    ]

    operations = [
    ]
